name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ECHO
      run: echo hello hi hey ho work
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
